apiVersion: v1
kind: Service
metadata:
  name: sky-weather-app-service
  namespace: sky-weather
spec:
  selector:
    app: sky-weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

